server:
  port: 1234
  servlet:
    context-path: /todolist

spring:
  datasource:
    username: jamisonm
    password: Randomdogpark
    url: jdbc:postgresql://todolist.cwi3jukycyjs.us-east-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
